//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GlCircle : GlOval
{
	public override float RadA
	{
		get

		{
			throw new System.NotImplementedException();
		}
		set

		{
			throw new System.NotImplementedException();
		}
	}

	public override float RadB
	{
		get

		{
			throw new System.NotImplementedException();
		}
		set

		{
			throw new System.NotImplementedException();
		}
	}

	public GlCircle(float Rad, GlPointR2 center)
	{
	}

	public GlCircle(GlCircle copyCircle)
	{
	}

	public override string ToString()
	{
		throw new System.NotImplementedException();
	}

}

