//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GlColor
{
	private float Rv;

	private float Gv;

	private float Bv;

	public virtual float B
	{
		get

		{
			throw new System.NotImplementedException();
		}
		set

		{
			throw new System.NotImplementedException();
		}
	}

	public virtual float R
	{
		get

		{
			throw new System.NotImplementedException();
		}
		set

		{
			throw new System.NotImplementedException();
		}
	}

	public virtual float G
	{
		get

		{
			throw new System.NotImplementedException();
		}
		set

		{
			throw new System.NotImplementedException();
		}
	}

	public GlColor(short R, short G, short B)
	{
	}

	public GlColor(GlColor copyColor)
	{
	}

	public GlColor(float R, float G, float B)
	{
	}

	public virtual void setColor(short R, short G, short B)
	{
		throw new System.NotImplementedException();
	}

	public virtual void invertColor()
	{
		throw new System.NotImplementedException();
	}

	public static float Validate(float value)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Validate(GlColor color)
	{
		throw new System.NotImplementedException();
	}

	public static bool Equals(GlColor C1, GlColor C2)
	{
		throw new System.NotImplementedException();
	}

}

