//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GlPolygon : GlFigure
{
	private const float FAULT = 0.01f;

	public override int CountOfPoints
	{
		get

		{
			throw new System.NotImplementedException();
		}
		private set

		{
			throw new System.NotImplementedException();
		}
	}

	public override GlPointR2 Center
	{
		get

		{
			throw new System.NotImplementedException();
		}
		private set

		{
			throw new System.NotImplementedException();
		}
	}

	public override GlRectangle BOX
	{
		get

		{
			throw new System.NotImplementedException();
		}
		private set

		{
			throw new System.NotImplementedException();
		}
	}

	public virtual float CenterX
	{
		get

		{
			throw new System.NotImplementedException();
		}
		set

		{
			throw new System.NotImplementedException();
		}
	}

	public virtual float CenterY
	{
		get

		{
			throw new System.NotImplementedException();
		}
		set

		{
			throw new System.NotImplementedException();
		}
	}

	public virtual float P
	{
		get;
		protected set;
	}

	public virtual float S
	{
		get;
		protected set;
	}

	public event VertexAddStart OnVertexAddingStart;

	public event VertexAdd OnVertexAdded;

	public event VertexAdd OnVertexAdding;

	private IEnumerable<GlPointR2> vertexes;

	private GlPointR2 polyCenter;

	public virtual VertexAddStart VertexAddStart
	{
		get;
		set;
	}

	public virtual VertexAdd VertexAdd
	{
		get;
		set;
	}

	public override void moveTo(float x, float y)
	{
		throw new System.NotImplementedException();
	}

	public override void Rotate(float angle)
	{
		throw new System.NotImplementedException();
	}

	public override void Rotate(float SIN, float COS)
	{
		throw new System.NotImplementedException();
	}

	public override GlFigure getScaled(float scale)
	{
		throw new System.NotImplementedException();
	}

	public override IEnumerable<GlPointR2> getIntersection(GlLineR2 L)
	{
		throw new System.NotImplementedException();
	}

	public override IEnumerable<GlPointR2> getIntersection(GlCurve C)
	{
		throw new System.NotImplementedException();
	}

	public override IEnumerable<GlPointR2> getIntersection(GlPolygon POLY)
	{
		throw new System.NotImplementedException();
	}

	public override bool isPointBelongs(GlPointR2 P)
	{
		throw new System.NotImplementedException();
	}

	public override void Draw()
	{
		throw new System.NotImplementedException();
	}

	public override void DrawFill()
	{
		throw new System.NotImplementedException();
	}

	public override void Draw(GlTexture T)
	{
		throw new System.NotImplementedException();
	}

	public override void Draw(GlRectangle Border)
	{
		throw new System.NotImplementedException();
	}

	public override void DrawFill(GlRectangle Border)
	{
		throw new System.NotImplementedException();
	}

	private void ActivateDrawed()
	{
		throw new System.NotImplementedException();
	}

	private void ActivateDrawing()
	{
		throw new System.NotImplementedException();
	}

	private bool ActivateDrawStart()
	{
		throw new System.NotImplementedException();
	}

	private void DrawPoints(GlRectangle Border, int GlDrawMode)
	{
		throw new System.NotImplementedException();
	}

	private void DrawPoints(int GlDrawMode)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool isPointInside(GlPointR2 P)
	{
		throw new System.NotImplementedException();
	}

	public virtual void addVertex(GlPointR2 P)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool Equals(object obj)
	{
		throw new System.NotImplementedException();
	}

	public virtual string ToString()
	{
		throw new System.NotImplementedException();
	}

	public virtual GlPointR2 this[int i]
	{
		get
		{
			throw new System.NotImplementedException();
		}
		set
		{
			throw new System.NotImplementedException();
		}
	}

	public GlPolygon(GlPointR2 center, IEnumerable<GlPointR2> initPoints)
	{
	}

	public GlPolygon(GlPolygon copyPolygon)
	{
	}

}

