//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GlRectangle : GlPolygon
{
	private GlVectorR2 directVector;

	private GlPointR2 leftTopPoint;

	public virtual GlVectorR2 DirectVector
	{
		get

		{
			throw new System.NotImplementedException();
		}
		private set

		{
			throw new System.NotImplementedException();
		}
	}

	public virtual GlPointR2 LeftTopPoint
	{
		get

		{
			throw new System.NotImplementedException();
		}
		private set

		{
			throw new System.NotImplementedException();
		}
	}

	public virtual float Width
	{
		get

		{
			throw new System.NotImplementedException();
		}
		private set

		{
			throw new System.NotImplementedException();
		}
	}

	public virtual float Height
	{
		get

		{
			throw new System.NotImplementedException();
		}
		private set

		{
			throw new System.NotImplementedException();
		}
	}

	public GlRectangle(GlPointR2 PLT, float width, float height, GlVectorR2 directVector)
	{
	}

	public GlRectangle(GlRectangle copyRectangle)
	{
	}

	public override void addVertex(GlPointR2 P)
	{
		throw new System.NotImplementedException();
	}

}

