//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GlTriangle : GlPolygon
{
	public GlTriangle(GlPointR2 P1, GlPointR2 P2, GlPointR2 P3)
	{
	}

	public GlTriangle(GlTriangle copyTriangle)
	{
	}

	public override void addVertex(GlPointR2 P)
	{
		throw new System.NotImplementedException();
	}

}

